name: github workflow context
on:
 push
jobs:
  build_job:
   runs-on: ubuntu-latest
   steps:
    - name: context-worflow
      run: |
        echo "event_name ${{ github.event_name }}"
        echo "reference_name ${{ github.ref }}"
        echo "sha_value ${{ github.sha }}"
        echo "actor_name ${{ github.actor }}"
        echo "workflow_name ${{ github.workflow }}"
        echo "run_id ${{ github.run_id }}"
        echo "run_number ${{ github.run_number }}"
        
        
   
